sudo: false

language: erlang

python:
  - "3.4"

before_install:
  - pip install --user cpp-coveralls

install:
  - rebar get-deps

after_success:
  - coveralls --exclude lib --exclude tests --gcov-options '\-lp'

otp_release:
  - 17.1
  - 17.5
  - 18.0
